<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Student;
use App\Models\Classroom;
use App\Models\AcademicPeriod;
use App\Models\Enrollment;
use Spatie\Permission\Models\Role;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Data Lengkap Siswa (97 Data Valid dari File 8355 YG BARU.xlsx)
        $studentsData = [
            [
                'name' => 'ABDUL WAHAB ALGHIFARI',
                'nipd' => '25.396',
                'gender' => 'L',
                'nisn' => '3137254227',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2013-05-18',
                'nik' => '1303041805130002',
                'religion' => 'Islam',
                'address' => 'JORONG ILIE GUGUK DADOK',
                'father_name' => 'ZULFIANDI',
                'mother_name' => 'SAKDIAH',
                'rombel' => '7/1',
            ],
            [
                'name' => 'Afiq Zaqwan',
                'nipd' => '25.397',
                'gender' => 'L',
                'nisn' => '0126937422',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-06-27',
                'nik' => '1303042706120003',
                'religion' => 'Islam',
                'address' => 'Jororng Limau Sundai',
                'father_name' => 'Zulhendra',
                'mother_name' => 'Devi Wardinata',
                'rombel' => '7/1',
            ],
            [
                'name' => 'AHMAD QOLBI MAULANA',
                'nipd' => '25.398',
                'gender' => 'L',
                'nisn' => '0132769471',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-01-21',
                'nik' => '1303042101130003',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah Muaro',
                'father_name' => 'Reno Pratama',
                'mother_name' => 'Dela Septrina',
                'rombel' => '7/1',
            ],
            [
                'name' => 'AINIL MARDIAH',
                'nipd' => '25.399',
                'gender' => 'P',
                'nisn' => '0136115114',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-01-07',
                'nik' => '1303044701130003',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Afri Wandi',
                'mother_name' => 'Melda Ayani',
                'rombel' => '7/1',
            ],
            [
                'name' => 'AMRIZAL ISMI',
                'nipd' => '25,400',
                'gender' => 'L',
                'nisn' => '3139857712',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-04-30',
                'nik' => '1303043004130001',
                'religion' => 'Islam',
                'address' => 'Syech Abdul Wahab',
                'father_name' => 'JONI ISKANDAR',
                'mother_name' => 'IRDA NINGSIH',
                'rombel' => '7/1',
            ],
            [
                'name' => 'ARFA ARJUNA PUTRA',
                'nipd' => '25.401',
                'gender' => 'L',
                'nisn' => '3126563561',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-06-23',
                'nik' => '1303042306120002',
                'religion' => 'Islam',
                'address' => 'JALAN IMAM BONJOL NO 75',
                'father_name' => 'EDI LASWARDI',
                'mother_name' => 'ERNAWILIS',
                'rombel' => '7/1',
            ],
            [
                'name' => 'ARFAN HASHIF',
                'nipd' => '25.402',
                'gender' => 'L',
                'nisn' => '3137481786',
                'place_of_birth' => 'Solok',
                'date_of_birth' => '2013-03-02',
                'nik' => '1303040203130001',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak',
                'father_name' => 'YANUAR',
                'mother_name' => 'DESMANIAR',
                'rombel' => '7/1',
            ],
            [
                'name' => 'AUREL BILQIS NAWAFI',
                'nipd' => '25.403',
                'gender' => 'P',
                'nisn' => '3128150730',
                'place_of_birth' => 'Solok',
                'date_of_birth' => '2012-04-06',
                'nik' => '1303044604120002',
                'religion' => 'Islam',
                'address' => 'Jorong Hilie Pasar Juma\'at',
                'father_name' => '',
                'mother_name' => 'Mega Selvia',
                'rombel' => '7/1',
            ],
            [
                'name' => 'GAVI ALFARO',
                'nipd' => '25.404',
                'gender' => 'L',
                'nisn' => '0138580346',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-06-16',
                'nik' => '1303041606130002',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Alprimadona',
                'mother_name' => 'Salmiati',
                'rombel' => '7/1',
            ],
            [
                'name' => 'HAYKAL GAUTAMA',
                'nipd' => '25.405',
                'gender' => 'L',
                'nisn' => '0124146014',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-12-03',
                'nik' => '1303040312120001',
                'religion' => 'Islam',
                'address' => 'JORONG SUBARANG SUKAM',
                'father_name' => 'SYAFRIADI',
                'mother_name' => 'NENGSI BETRIA',
                'rombel' => '7/1',
            ],
            [
                'name' => 'HENDRA',
                'nipd' => '25.406',
                'gender' => 'L',
                'nisn' => '0114630803',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-11-06',
                'nik' => '1303040611110001',
                'religion' => 'Islam',
                'address' => 'JORONG PAMATANG ANJUNG',
                'father_name' => 'PENDI',
                'mother_name' => 'TUTI HERAWATI',
                'rombel' => '7/1',
            ],
            [
                'name' => 'KAMIL ZAHY NANGDIKA PUTRA',
                'nipd' => '25.407',
                'gender' => 'L',
                'nisn' => '0133158614',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-01-04',
                'nik' => '1303040401130001',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjung',
                'father_name' => 'NOFRIKA PUTRA',
                'mother_name' => 'NENGSIH OKTAVIA',
                'rombel' => '7/1',
            ],
            [
                'name' => 'KHAIRAN RASYID',
                'nipd' => '25.408',
                'gender' => 'L',
                'nisn' => '0131468314',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2013-05-02',
                'nik' => '1303040205130001',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'PURBA',
                'mother_name' => 'LENI MARLINA',
                'rombel' => '7/1',
            ],
            [
                'name' => 'MITA JUNATA PUTRI',
                'nipd' => '25.409',
                'gender' => 'P',
                'nisn' => '0139724912',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-01-07',
                'nik' => '1303044701130002',
                'religion' => 'Islam',
                'address' => 'Syech Abdul Wahab',
                'father_name' => 'PERI',
                'mother_name' => 'RAHMAYULIS',
                'rombel' => '7/1',
            ],
            [
                'name' => 'Muhammad Arya',
                'nipd' => '25,410',
                'gender' => 'L',
                'nisn' => '0117753101',
                'place_of_birth' => 'Solok',
                'date_of_birth' => '2011-09-04',
                'nik' => '1303040409110001',
                'religion' => 'Islam',
                'address' => 'Jorong Limau Sundai',
                'father_name' => 'Don Hendri',
                'mother_name' => 'Ria Astuti',
                'rombel' => '7/1',
            ],
            [
                'name' => 'MUHAMMAD FAIZIL SAPUTRA',
                'nipd' => '25.411',
                'gender' => 'L',
                'nisn' => '0112868162',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-02-15',
                'nik' => '1303041502110001',
                'religion' => 'Islam',
                'address' => 'Kabun',
                'father_name' => 'Iskandar',
                'mother_name' => 'Ernawati',
                'rombel' => '7/1',
            ],
            [
                'name' => 'Muhammad Zahid',
                'nipd' => '25.412',
                'gender' => 'L',
                'nisn' => '0111954211',
                'place_of_birth' => 'Gantung Ciri',
                'date_of_birth' => '2011-06-11',
                'nik' => '1302101106110002',
                'religion' => 'Islam',
                'address' => 'markio',
                'father_name' => 'Igen',
                'mother_name' => 'Wita Sucianti',
                'rombel' => '7/1',
            ],
            [
                'name' => 'NADIRA HENDRI RIA MARSA',
                'nipd' => '25.413',
                'gender' => 'P',
                'nisn' => '0128041945',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-09-13',
                'nik' => '1303045309120002',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUANG',
                'father_name' => 'HENDRA EKA PUTRA',
                'mother_name' => 'RIA PURNAMA DEWI',
                'rombel' => '7/1',
            ],
            [
                'name' => 'NOVEL FITRA ANUGRAH',
                'nipd' => '25.414',
                'gender' => 'L',
                'nisn' => '0129356014',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-11-24',
                'nik' => '1303042411120001',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUANG',
                'father_name' => 'JAMARIS',
                'mother_name' => 'YUNITA SARI',
                'rombel' => '7/1',
            ],
            [
                'name' => 'NURHAZIZAH SABRINA',
                'nipd' => '25.415',
                'gender' => 'P',
                'nisn' => '0134018485',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2013-03-27',
                'nik' => '1303046703130001',
                'religion' => 'Islam',
                'address' => 'JORONG ILIE PASA JUMAK',
                'father_name' => 'JASRIMAN',
                'mother_name' => 'RESTI',
                'rombel' => '7/1',
            ],
            [
                'name' => 'RAFFI OKTAVIANSYAH',
                'nipd' => '25.416',
                'gender' => 'L',
                'nisn' => '0126219086',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-10-08',
                'nik' => '1303040810120002',
                'religion' => 'Islam',
                'address' => 'Syech Abdul Wahab',
                'father_name' => 'PULIN',
                'mother_name' => 'MAHANIAR',
                'rombel' => '7/1',
            ],
            [
                'name' => 'RIMA SALSA SAFITRI',
                'nipd' => '25.417',
                'gender' => 'P',
                'nisn' => '0126371324',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-08-31',
                'nik' => '1303047108120001',
                'religion' => 'Islam',
                'address' => 'JALAN SISINGAMANGARAJA',
                'father_name' => 'AFRIZAL',
                'mother_name' => 'ELSA WAHYUNI',
                'rombel' => '7/1',
            ],
            [
                'name' => 'Trio Syaputra',
                'nipd' => '25.418',
                'gender' => 'L',
                'nisn' => '0117603767',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-03-24',
                'nik' => '1303042403110001',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah',
                'father_name' => 'Yodi Hendra',
                'mother_name' => 'Yuliama',
                'rombel' => '7/1',
            ],
            [
                'name' => 'ALFARUQI DAFFA SYAFINDRA',
                'nipd' => '25.419',
                'gender' => 'L',
                'nisn' => '0123252425',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-10-14',
                'nik' => '1303041410120001',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUANG',
                'father_name' => 'INDRA',
                'mother_name' => 'SYAFINAR',
                'rombel' => '7/2',
            ],
            [
                'name' => 'ANUGRAH RIZKY PRATAMA',
                'nipd' => '25,420',
                'gender' => 'L',
                'nisn' => '0139560502',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-05-06',
                'nik' => '1303040605130001',
                'religion' => 'Islam',
                'address' => 'Syech Abdul Wahab',
                'father_name' => 'JONDRIZAL',
                'mother_name' => 'RINI NURJANI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'BADAI RAZAKI',
                'nipd' => '25.421',
                'gender' => 'L',
                'nisn' => '0134068666',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-03-12',
                'nik' => '1303041203130001',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Dasril',
                'mother_name' => 'Siti Mardewi',
                'rombel' => '7/2',
            ],
            [
                'name' => 'BAFIO PUTRA',
                'nipd' => '25.422',
                'gender' => 'L',
                'nisn' => '3130984703',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-01-24',
                'nik' => '1303042401130002',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah',
                'father_name' => 'Syafar Filto',
                'mother_name' => 'Vitrima',
                'rombel' => '7/2',
            ],
            [
                'name' => 'DAUD PERLINDUNGAN SIREGAR',
                'nipd' => '25.423',
                'gender' => 'L',
                'nisn' => '3126303200',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-12-29',
                'nik' => '1303042912120006',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Ali Amad Siregar',
                'mother_name' => 'Rita Sari Bunda',
                'rombel' => '7/2',
            ],
            [
                'name' => 'DIKA RAMADANA PUTRA',
                'nipd' => '25.424',
                'gender' => 'L',
                'nisn' => '0123164288',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-08-04',
                'nik' => '1303040408120001',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Guguk Dadok',
                'father_name' => 'ZULHAM YUNUS',
                'mother_name' => 'NURATI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'Fajar Saputra',
                'nipd' => '25.425',
                'gender' => 'L',
                'nisn' => '0093300323',
                'place_of_birth' => 'Muaro',
                'date_of_birth' => '2009-12-20',
                'nik' => '1303042012090007',
                'religion' => 'Islam',
                'address' => 'Jl. Syech abdul Wahab',
                'father_name' => 'SIUN',
                'mother_name' => 'NURMAINI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'HADIL SATRIA MAULANA',
                'nipd' => '25.426',
                'gender' => 'L',
                'nisn' => '0121740165',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-12-23',
                'nik' => '1303042312120001',
                'religion' => 'Islam',
                'address' => 'JORONG HILIE PASAR JUMAT',
                'father_name' => 'DASRUL',
                'mother_name' => 'NURAJI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'Harza Zola',
                'nipd' => '25.427',
                'gender' => 'L',
                'nisn' => '0129670028',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-07-02',
                'nik' => '1303040207120001',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjung',
                'father_name' => 'Usriman',
                'mother_name' => 'Setri Efnita',
                'rombel' => '7/2',
            ],
            [
                'name' => 'LATHIFAH ISMU FAUZIAH',
                'nipd' => '25.428',
                'gender' => 'P',
                'nisn' => '3127374899',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-08-22',
                'nik' => '1303046208120002',
                'religion' => 'Islam',
                'address' => 'Jorong Subarang Sukam Muaro',
                'father_name' => 'Bujang Tenus',
                'mother_name' => 'Nurhayati',
                'rombel' => '7/2',
            ],
            [
                'name' => 'MIKEYLAH EGITA ZAHRA',
                'nipd' => '25.429',
                'gender' => 'P',
                'nisn' => '3129246599',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-09-09',
                'nik' => '1303044909120001',
                'religion' => 'Islam',
                'address' => 'JR. SUBARANG SUKAM',
                'father_name' => 'SUGIANTO',
                'mother_name' => 'RISNAWATI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'NOVEL AULIA SARI DEWI',
                'nipd' => '25,430',
                'gender' => 'P',
                'nisn' => '3132413205',
                'place_of_birth' => 'SOLOK',
                'date_of_birth' => '2013-01-23',
                'nik' => '1302106301130003',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUNG',
                'father_name' => 'SICAP',
                'mother_name' => 'YANDRAWATI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'RAZIK HANAN FEBRIANTO',
                'nipd' => '25.431',
                'gender' => 'L',
                'nisn' => '0135613862',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2013-02-03',
                'nik' => '1303040302130002',
                'religion' => 'Islam',
                'address' => 'JALAN KEMUNING',
                'father_name' => 'JEFRI',
                'mother_name' => 'RINE WIRDANI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'Rehan Purnama Putra',
                'nipd' => '25.432',
                'gender' => 'L',
                'nisn' => '3137877899',
                'place_of_birth' => 'Solok',
                'date_of_birth' => '2013-03-14',
                'nik' => '1302071403130000',
                'religion' => 'Islam',
                'address' => 'Jorong Talago',
                'father_name' => 'Asril',
                'mother_name' => 'Desyerni',
                'rombel' => '7/2',
            ],
            [
                'name' => 'RIZKY AHMAD',
                'nipd' => '25.433',
                'gender' => 'L',
                'nisn' => '3132257105',
                'place_of_birth' => 'sijunjung',
                'date_of_birth' => '2013-04-05',
                'nik' => '1303040504130001',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah',
                'father_name' => '',
                'mother_name' => 'Hasniwar',
                'rombel' => '7/2',
            ],
            [
                'name' => 'SALMAN SAUGI ALWAFI',
                'nipd' => '25.434',
                'gender' => 'L',
                'nisn' => '0131140380',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2013-01-21',
                'nik' => '1303042101130001',
                'religion' => 'Islam',
                'address' => 'JORONG HILIE PASA JUMAK',
                'father_name' => 'SAFRI MONTI BESAR',
                'mother_name' => 'DESI SASTRA YULIANA',
                'rombel' => '7/2',
            ],
            [
                'name' => 'SAPTORIANDA JAMIN',
                'nipd' => '25.435',
                'gender' => 'L',
                'nisn' => '0126433011',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-05-12',
                'nik' => '1303041205120002',
                'religion' => 'Islam',
                'address' => 'JALAN IMAM BONJOL',
                'father_name' => 'UJANG',
                'mother_name' => 'SUGIARTIK',
                'rombel' => '7/2',
            ],
            [
                'name' => 'TRI RAHMAD DHANI',
                'nipd' => '25.436',
                'gender' => 'L',
                'nisn' => '0111793685',
                'place_of_birth' => 'Solok',
                'date_of_birth' => '2011-08-03',
                'nik' => '1303040308110001',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah',
                'father_name' => '',
                'mother_name' => 'Mardayanti',
                'rombel' => '7/2',
            ],
            [
                'name' => 'TRI VIOLA RAMADANI',
                'nipd' => '25.437',
                'gender' => 'P',
                'nisn' => '3127388554',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-07-25',
                'nik' => '1303046507120002',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Suherman',
                'mother_name' => 'Nopi Repelita',
                'rombel' => '7/2',
            ],
            [
                'name' => 'VIRZI FITRIANI',
                'nipd' => '25.438',
                'gender' => 'P',
                'nisn' => '0133204240',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-03-04',
                'nik' => '1303044403130002',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang  Anjung',
                'father_name' => 'Riski',
                'mother_name' => 'WANI FITRA',
                'rombel' => '7/2',
            ],
            [
                'name' => 'WILFA SEPRUDANI',
                'nipd' => '25.439',
                'gender' => 'P',
                'nisn' => '3121395139',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-09-16',
                'nik' => '1303045609120002',
                'religion' => 'Islam',
                'address' => 'GANTIANG',
                'father_name' => 'IRUN PADUKO RAJO',
                'mother_name' => 'INDRAWATI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'YUDA WADI SAPUTRA',
                'nipd' => '25,440',
                'gender' => 'L',
                'nisn' => '0124203875',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-06-02',
                'nik' => '1303040206120002',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Junaidi',
                'mother_name' => 'Wati Herawati',
                'rombel' => '7/2',
            ],
            [
                'name' => 'ZIDAN RAFELLO RIOZA',
                'nipd' => '25.441',
                'gender' => 'L',
                'nisn' => '0123168238',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-12-30',
                'nik' => '1303043012120001',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Rio Oktoridho',
                'mother_name' => 'Azizah',
                'rombel' => '7/2',
            ],
            [
                'name' => 'CELCYE YULPEN OKTAFIANI',
                'nipd' => '\'23.340',
                'gender' => 'P',
                'nisn' => '0093972665',
                'place_of_birth' => 'MUARO',
                'date_of_birth' => '2009-10-22',
                'nik' => '1303046210090001',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Pendi Taruna Jaya',
                'mother_name' => 'Yusneli',
                'rombel' => '9/1',
            ],
            [
                'name' => 'FAHLAN MAHENDRA',
                'nipd' => '23.342',
                'gender' => 'L',
                'nisn' => '0106206109',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-03-07',
                'nik' => '1303040703100003',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUNG',
                'father_name' => 'ASEP SAPUTRA',
                'mother_name' => 'ISGUSNAWATI',
                'rombel' => '9/1',
            ],
            [
                'name' => 'GALANG RAMADHAN',
                'nipd' => '23.343',
                'gender' => 'L',
                'nisn' => '0104003706',
                'place_of_birth' => 'MUARO',
                'date_of_birth' => '2010-08-18',
                'nik' => '1303041808100001',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Misno',
                'mother_name' => 'Fenni Mawina',
                'rombel' => '9/1',
            ],
            [
                'name' => 'GHIANA SEPTIA NOVICHA',
                'nipd' => '23.344',
                'gender' => 'P',
                'nisn' => '0104586922',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-09-01',
                'nik' => '1303044109100003',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Nofrizal',
                'mother_name' => 'Icha Siskawati',
                'rombel' => '9/1',
            ],
            [
                'name' => 'TRI RAHMAD DHANI',
                'nipd' => '25.436',
                'gender' => 'L',
                'nisn' => '0111793685',
                'place_of_birth' => 'Solok',
                'date_of_birth' => '2011-08-03',
                'nik' => '1303040308110001',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah',
                'father_name' => '',
                'mother_name' => 'Mardayanti',
                'rombel' => '7/2',
            ],
            [
                'name' => 'TRI VIOLA RAMADANI',
                'nipd' => '25.437',
                'gender' => 'P',
                'nisn' => '3127388554',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-07-25',
                'nik' => '1303046507120002',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Suherman',
                'mother_name' => 'Nopi Repelita',
                'rombel' => '7/2',
            ],
            [
                'name' => 'VIRZI FITRIANI',
                'nipd' => '25.438',
                'gender' => 'P',
                'nisn' => '0133204240',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2013-03-04',
                'nik' => '1303044403130002',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang  Anjung',
                'father_name' => 'Riski',
                'mother_name' => 'WANI FITRA',
                'rombel' => '7/2',
            ],
            [
                'name' => 'WILFA SEPRUDANI',
                'nipd' => '25.439',
                'gender' => 'P',
                'nisn' => '3121395139',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-09-16',
                'nik' => '1303045609120002',
                'religion' => 'Islam',
                'address' => 'GANTIANG',
                'father_name' => 'IRUN PADUKO RAJO',
                'mother_name' => 'INDRAWATI',
                'rombel' => '7/2',
            ],
            [
                'name' => 'YUDA WADI SAPUTRA',
                'nipd' => '25,440',
                'gender' => 'L',
                'nisn' => '0124203875',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-06-02',
                'nik' => '1303040206120002',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Junaidi',
                'mother_name' => 'Wati Herawati',
                'rombel' => '7/2',
            ],
            [
                'name' => 'ZIDAN RAFELLO RIOZA',
                'nipd' => '25.441',
                'gender' => 'L',
                'nisn' => '0123168238',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-12-30',
                'nik' => '1303043012120001',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Rio Oktoridho',
                'mother_name' => 'Azizah',
                'rombel' => '7/2',
            ],
            [
                'name' => 'CELCYE YULPEN OKTAFIANI',
                'nipd' => '\'23.340',
                'gender' => 'P',
                'nisn' => '0093972665',
                'place_of_birth' => 'MUARO',
                'date_of_birth' => '2009-10-22',
                'nik' => '1303046210090001',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Pendi Taruna Jaya',
                'mother_name' => 'Yusneli',
                'rombel' => '9/1',
            ],
            [
                'name' => 'FAHLAN MAHENDRA',
                'nipd' => '23.342',
                'gender' => 'L',
                'nisn' => '0106206109',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-03-07',
                'nik' => '1303040703100003',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUNG',
                'father_name' => 'ASEP SAPUTRA',
                'mother_name' => 'ISGUSNAWATI',
                'rombel' => '9/1',
            ],
            [
                'name' => 'GALANG RAMADHAN',
                'nipd' => '23.343',
                'gender' => 'L',
                'nisn' => '0104003706',
                'place_of_birth' => 'MUARO',
                'date_of_birth' => '2010-08-18',
                'nik' => '1303041808100001',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Misno',
                'mother_name' => 'Fenni Mawina',
                'rombel' => '9/1',
            ],
            [
                'name' => 'GHIANA SEPTIA NOVICHA',
                'nipd' => '23.344',
                'gender' => 'P',
                'nisn' => '0104586922',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-09-01',
                'nik' => '1303044109100003',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Anjuang Muaro',
                'father_name' => 'Nofrizal',
                'mother_name' => 'Icha Siskawati',
                'rombel' => '9/1',
            ],
            [
                'name' => 'Gusti Gangga Pratama',
                'nipd' => '23.345',
                'gender' => 'L',
                'nisn' => '0085037333',
                'place_of_birth' => 'Pamatang Panjang',
                'date_of_birth' => '2008-12-09',
                'nik' => '1303040912080003',
                'religion' => 'Islam',
                'address' => 'Jln. Sisingamangaraja',
                'father_name' => 'Musrizal',
                'mother_name' => 'Dida Rosida',
                'rombel' => '9/1',
            ],
            [
                'name' => 'INTAN AURA FEBRIANTI',
                'nipd' => '23.346',
                'gender' => 'P',
                'nisn' => '0104674577',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-02-09',
                'nik' => '1303044902100001',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUNG',
                'father_name' => 'RISRIANTO',
                'mother_name' => 'GUSNAINI',
                'rombel' => '9/1',
            ],
            [
                'name' => 'JEFRI DESRIANTO',
                'nipd' => '23.347',
                'gender' => 'L',
                'nisn' => '0075326946',
                'place_of_birth' => 'PADANG',
                'date_of_birth' => '2007-12-01',
                'nik' => '1371060112070004',
                'religion' => 'Islam',
                'address' => 'Jalan Imam Bonjol',
                'father_name' => 'Bambang Irwanto',
                'mother_name' => 'NOVERITA',
                'rombel' => '9/1',
            ],
            [
                'name' => 'M. Hendra Cahaya',
                'nipd' => '23.348',
                'gender' => 'L',
                'nisn' => '0107702128',
                'place_of_birth' => 'Padang',
                'date_of_birth' => '2010-07-15',
                'nik' => '1303041507100002',
                'religion' => 'Islam',
                'address' => 'Jorong ilie Guguk Dadok',
                'father_name' => 'Zulham Yunus',
                'mother_name' => 'Siska Kurnia Zuriati',
                'rombel' => '9/1',
            ],
            [
                'name' => 'MELIZA OLIVIA TIARA PUTRI',
                'nipd' => '23.349',
                'gender' => 'P',
                'nisn' => '0115725692',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-05-23',
                'nik' => '1303046305110002',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUANG',
                'father_name' => 'NAJO PURWADI',
                'mother_name' => 'LILI SARIANI',
                'rombel' => '9/1',
            ],
            [
                'name' => 'MUHAMMAD ARIFANDI',
                'nipd' => '23.351',
                'gender' => 'L',
                'nisn' => '0105116670',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-10-30',
                'nik' => '1303043010100002',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah Muaro',
                'father_name' => 'Daral Fauzi',
                'mother_name' => 'Elva Neldawati',
                'rombel' => '9/1',
            ],
            [
                'name' => 'MUHAMMAD HENDRI',
                'nipd' => '23.352',
                'gender' => 'L',
                'nisn' => '0095793303',
                'place_of_birth' => 'RANAH SIGADING',
                'date_of_birth' => '2009-11-28',
                'nik' => '1303042811090002',
                'religion' => 'Islam',
                'address' => 'jl. raya batu balang',
                'father_name' => 'pendi',
                'mother_name' => 'tuti herawati',
                'rombel' => '9/1',
            ],
            [
                'name' => 'RAYNALDI FALGADISU',
                'nipd' => '23.354',
                'gender' => 'L',
                'nisn' => '0105558687',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2010-11-12',
                'nik' => '1303041211100001',
                'religion' => 'Islam',
                'address' => 'Syech Abdul Wahab',
                'father_name' => 'SAPRIANTO',
                'mother_name' => 'SARTINI',
                'rombel' => '9/1',
            ],
            [
                'name' => 'Satria Riski Pratama',
                'nipd' => '23.359',
                'gender' => 'L',
                'nisn' => '0104951478',
                'place_of_birth' => 'Solok',
                'date_of_birth' => '2010-12-03',
                'nik' => '1303080312100002',
                'religion' => 'Islam',
                'address' => 'Selayo',
                'father_name' => 'Abang Tajudin',
                'mother_name' => 'Sri Wahyuni',
                'rombel' => '9/1',
            ],
            [
                'name' => 'Sri Reno Nilan',
                'nipd' => '23.355',
                'gender' => 'P',
                'nisn' => '0106958315',
                'place_of_birth' => 'Tanah Datar',
                'date_of_birth' => '2010-04-06',
                'nik' => '1303044604100001',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Guguk Dadok',
                'father_name' => 'Rismaldi',
                'mother_name' => 'Yanti',
                'rombel' => '9/1',
            ],
            [
                'name' => 'TASYA ADELIA SAFITRI',
                'nipd' => '23.356',
                'gender' => 'P',
                'nisn' => '0082160428',
                'place_of_birth' => 'PEMATANG PANJANG',
                'date_of_birth' => '2008-12-20',
                'nik' => '1303046012080003',
                'religion' => 'Islam',
                'address' => 'JORONG KAMBUIK KOMAN',
                'father_name' => 'ASEP SAPUTRA',
                'mother_name' => 'ISGUSNAWATI',
                'rombel' => '9/1',
            ],
            [
                'name' => 'Zahra Putri Yandes',
                'nipd' => '25.444',
                'gender' => 'P',
                'nisn' => '0116031333',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-06-26',
                'nik' => '1303046606110002',
                'religion' => 'Islam',
                'address' => 'Muara lembu',
                'father_name' => 'Yanuar',
                'mother_name' => 'Desmaniar',
                'rombel' => '9/1',
            ],
            [
                'name' => 'Ahmad Habibie',
                'nipd' => '24.364',
                'gender' => 'L',
                'nisn' => '0127027390',
                'place_of_birth' => 'Muaro',
                'date_of_birth' => '2012-01-27',
                'nik' => '1303042701120004',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Panjang',
                'father_name' => 'Novendri',
                'mother_name' => 'Heni Puspita Sari',
                'rombel' => '8/1',
            ],
            [
                'name' => 'Ahmad Solihin',
                'nipd' => '24.365',
                'gender' => 'L',
                'nisn' => '0106206109',
                'place_of_birth' => 'Muaro',
                'date_of_birth' => '2010-12-09',
                'nik' => '1303040912100001',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Panjang',
                'father_name' => 'Syafrizal',
                'mother_name' => 'Eli Novera',
                'rombel' => '8/1',
            ],
            [
                'name' => 'Alifa Nindya Putri',
                'nipd' => '24.366',
                'gender' => 'P',
                'nisn' => '0112709292',
                'place_of_birth' => 'Muaro',
                'date_of_birth' => '2011-12-01',
                'nik' => '1303044112110002',
                'religion' => 'Islam',
                'address' => 'Jorong Subarang Sukam',
                'father_name' => 'Afri Yonaldi',
                'mother_name' => 'Susilawati',
                'rombel' => '8/1',
            ],
            [
                'name' => 'ANISA AULIA',
                'nipd' => '24.367',
                'gender' => 'P',
                'nisn' => '0121708239',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-02-14',
                'nik' => '1303045402120001',
                'religion' => 'Islam',
                'address' => 'GUGUK DADOK',
                'father_name' => 'HENDRI CAN',
                'mother_name' => 'ASNAWATI',
                'rombel' => '8/1',
            ],
            [
                'name' => 'AQILLA QAIRANI',
                'nipd' => '24.368',
                'gender' => 'P',
                'nisn' => '3116563608',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-11-20',
                'nik' => '1303046011110002',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'ISWANDI',
                'mother_name' => 'YUSNIMAR',
                'rombel' => '8/1',
            ],
            [
                'name' => 'AZKA MAULANA',
                'nipd' => '24.369',
                'gender' => 'L',
                'nisn' => '0117079251',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-08-25',
                'nik' => '1303042508110003',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'ALFIAN',
                'mother_name' => 'LOLI MARLINA',
                'rombel' => '8/1',
            ],
            [
                'name' => 'CITRA CANTIKA',
                'nipd' => '24.370',
                'gender' => 'P',
                'nisn' => '0115024449',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-09-02',
                'nik' => '1303044209110002',
                'religion' => 'Islam',
                'address' => 'JORONG GANTING',
                'father_name' => 'SYAFRIL',
                'mother_name' => 'ROSNIMAR',
                'rombel' => '8/1',
            ],
            [
                'name' => 'DARA AULIA PUTRI',
                'nipd' => '24.371',
                'gender' => 'P',
                'nisn' => '0129524458',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-01-20',
                'nik' => '1303046001120003',
                'religion' => 'Islam',
                'address' => 'JORONG GANTING',
                'father_name' => 'DASRIZAL',
                'mother_name' => 'ELDA SUSANTI',
                'rombel' => '8/1',
            ],
            [
                'name' => 'GIO VANNI',
                'nipd' => '24.374',
                'gender' => 'L',
                'nisn' => '0126742512',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2012-05-30',
                'nik' => '1303043005120002',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'JHON RINALDI',
                'mother_name' => 'WENNY GUSPITA',
                'rombel' => '8/1',
            ],
            [
                'name' => 'Haikal Putra',
                'nipd' => '24.375',
                'gender' => 'L',
                'nisn' => '0119286469',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-12-11',
                'nik' => '1303041112110003',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => 'Delfitra',
                'mother_name' => 'Nelvi Yanti',
                'rombel' => '8/1',
            ],
            [
                'name' => 'Jihan Talita Ulfa',
                'nipd' => '24.376',
                'gender' => 'P',
                'nisn' => '3119047721',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-09-02',
                'nik' => '1303044209110003',
                'religion' => 'Islam',
                'address' => 'Jorong Ganting',
                'father_name' => 'Amril',
                'mother_name' => 'Erawati',
                'rombel' => '8/1',
            ],
            [
                'name' => 'M. ALIF ALHADI',
                'nipd' => '24.379',
                'gender' => 'L',
                'nisn' => '0116813204',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-08-01',
                'nik' => '1303040108110001',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'HADIISMAN',
                'mother_name' => 'HERLENA',
                'rombel' => '8/1',
            ],
            [
                'name' => 'M. AZAM',
                'nipd' => '24.380',
                'gender' => 'L',
                'nisn' => '0112198007',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-08-01',
                'nik' => '1303040108110004',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'SAPRUDIN',
                'mother_name' => 'DEWI MURNI',
                'rombel' => '8/1',
            ],
            [
                'name' => 'Maulana Fajri',
                'nipd' => '24.381',
                'gender' => 'L',
                'nisn' => '0129758778',
                'place_of_birth' => 'Muaro',
                'date_of_birth' => '2012-03-24',
                'nik' => '1303042403120003',
                'religion' => 'Islam',
                'address' => 'Jorong Pematang Panjang',
                'father_name' => 'Irwan',
                'mother_name' => 'Novia Herlina',
                'rombel' => '8/1',
            ],
            [
                'name' => 'MUHAMMAD AZAM',
                'nipd' => '24.382',
                'gender' => 'L',
                'nisn' => '0114008123',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-07-28',
                'nik' => '1303042807110003',
                'religion' => 'Islam',
                'address' => 'JORONG ILIE PASA JUMAK',
                'father_name' => 'AFRIJON',
                'mother_name' => 'GUSRI YANTI',
                'rombel' => '8/1',
            ],
            [
                'name' => 'Muhammad Bintang Pratama',
                'nipd' => '24.383',
                'gender' => 'L',
                'nisn' => '3128911571',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-05-18',
                'nik' => '1303041805120002',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah',
                'father_name' => 'Efri Yanto',
                'mother_name' => 'Susilawati',
                'rombel' => '8/1',
            ],
            [
                'name' => 'MUHAMMAD RAFLI',
                'nipd' => '24.384',
                'gender' => 'L',
                'nisn' => '0116634591',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-09-08',
                'nik' => '1303040809110002',
                'religion' => 'Islam',
                'address' => 'JORONG ILIE PASA JUMAK',
                'father_name' => 'DASWANDI',
                'mother_name' => 'GUSNITA',
                'rombel' => '8/1',
            ],
            [
                'name' => 'MUHAMMAD REHAN',
                'nipd' => '24.385',
                'gender' => 'L',
                'nisn' => '0106886498',
                'place_of_birth' => 'PEMATANG PANJANG',
                'date_of_birth' => '2010-06-25',
                'nik' => '1303042506100004',
                'religion' => 'Islam',
                'address' => 'PEMATANG PANJANG',
                'father_name' => 'SAHRIL',
                'mother_name' => 'DESI RATNA SARI',
                'rombel' => '8/1',
            ],
            [
                'name' => 'Dzaky Adlan Hamizan',
                'nipd' => '24.372',
                'gender' => 'L',
                'nisn' => '0114678027',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-12-09',
                'nik' => '1303040912110001',
                'religion' => 'Islam',
                'address' => 'Jorong Ilie Pasa Jumak Muaro',
                'father_name' => '',
                'mother_name' => '',
                'rombel' => '8/2',
            ],
            [
                'name' => 'GALIH MARDIANSAH SAFRIMAN',
                'nipd' => '24.373',
                'gender' => 'L',
                'nisn' => '0118521399',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-03-21',
                'nik' => '1303042103110002',
                'religion' => 'Islam',
                'address' => 'Pematang Panjang',
                'father_name' => 'SYAFRIMAN NORA',
                'mother_name' => 'DEBI MARIANCE',
                'rombel' => '8/2',
            ],
            [
                'name' => 'Kanaya Mustama',
                'nipd' => '24.377',
                'gender' => 'P',
                'nisn' => '0115815269',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2011-09-27',
                'nik' => '1303046709110001',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah',
                'father_name' => 'Mustika Rahmat',
                'mother_name' => 'Irma Sepna Yahti',
                'rombel' => '8/2',
            ],
            [
                'name' => 'KARLISA DWI YANI',
                'nipd' => '24.378',
                'gender' => 'P',
                'nisn' => '0121410762',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-01-10',
                'nik' => '1303045001120003',
                'religion' => 'Islam',
                'address' => 'Syech Abdul Wahab',
                'father_name' => 'SOFIAN HADI',
                'mother_name' => 'AFRIDA YANTI',
                'rombel' => '8/2',
            ],
            [
                'name' => 'KESHA NABILA PUTRI',
                'nipd' => '24.395',
                'gender' => 'P',
                'nisn' => '0105399057',
                'place_of_birth' => 'PADANG',
                'date_of_birth' => '2010-06-06',
                'nik' => '1303044606100002',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'TAMBULIN',
                'mother_name' => 'ERNA',
                'rombel' => '8/2',
            ],
            [
                'name' => 'Kheyla Oktriyama Putri',
                'nipd' => '24.394',
                'gender' => 'P',
                'nisn' => '0124237930',
                'place_of_birth' => 'Sijunjung',
                'date_of_birth' => '2012-04-13',
                'nik' => '1303045304120002',
                'religion' => 'Islam',
                'address' => 'Jorong Subarang Sukam Muaro',
                'father_name' => 'Nofa Syofian Indra',
                'mother_name' => 'Fauziah. Z.Y',
                'rombel' => '8/2',
            ],
            [
                'name' => 'MUHAMMAD FATAH ALBARIQ',
                'nipd' => '24.383',
                'gender' => 'L',
                'nisn' => '0112702220',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-04-06',
                'nik' => '1303040604110001',
                'religion' => 'Islam',
                'address' => 'JORONG GANTING',
                'father_name' => 'YANTO',
                'mother_name' => 'NETTI HERAWATI',
                'rombel' => '8/2',
            ],
            [
                'name' => 'MUHAMMAD HAMDAN',
                'nipd' => '24.384',
                'gender' => 'L',
                'nisn' => '0118501250',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-03-31',
                'nik' => '1303047103110001',
                'religion' => 'Islam',
                'address' => 'JORONG GANTING',
                'father_name' => 'MASRIALDI',
                'mother_name' => 'NOVIA',
                'rombel' => '8/2',
            ],
            [
                'name' => 'MUHAMMAD IKHSAN',
                'nipd' => '24.385',
                'gender' => 'L',
                'nisn' => '0114008124',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-02-14',
                'nik' => '1303041402110003',
                'religion' => 'Islam',
                'address' => 'JORONG TANGAH',
                'father_name' => 'MASRIL',
                'mother_name' => 'NELVI YANTI',
                'rombel' => '8/2',
            ],
            [
                'name' => 'MUHAMMAD RIZKI',
                'nipd' => '24.386',
                'gender' => 'L',
                'nisn' => '0112423377',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-04-20',
                'nik' => '1303042004110002',
                'religion' => 'Islam',
                'address' => 'JORONG GANTING',
                'father_name' => 'ANDRI',
                'mother_name' => 'YENNI',
                'rombel' => '8/2',
            ],
            [
                'name' => 'MUTIARA HATI',
                'nipd' => '24.387',
                'gender' => 'P',
                'nisn' => '0106404983',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-09-02',
                'nik' => '1303040209100003',
                'religion' => 'Islam',
                'address' => 'JORONG GANTING',
                'father_name' => 'APRIYUS',
                'mother_name' => 'LOLI MARLINA',
                'rombel' => '8/2',
            ],
            [
                'name' => 'NOVAL YARDIANTO',
                'nipd' => '24.388',
                'gender' => 'L',
                'nisn' => '0099052121',
                'place_of_birth' => 'MUARO',
                'date_of_birth' => '2009-11-07',
                'nik' => '1303040711090002',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah Muaro',
                'father_name' => 'Yarmadi',
                'mother_name' => 'Elfa Liana',
                'rombel' => '8/2',
            ],
            [
                'name' => 'WIRA WIYANTI',
                'nipd' => '24.393',
                'gender' => 'P',
                'nisn' => '0112800351',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2011-03-30',
                'nik' => '1303047003110002',
                'religion' => 'Islam',
                'address' => 'JORONG PEMATANG ANJUNG',
                'father_name' => 'SUHU',
                'mother_name' => 'SINYAN',
                'rombel' => '8/2',
            ],
            [
                'name' => 'ZILIAN ALDRIN',
                'nipd' => '24.394',
                'gender' => 'L',
                'nisn' => '0105171307',
                'place_of_birth' => 'SIJUNJUNG',
                'date_of_birth' => '2010-07-25',
                'nik' => '1303042507100002',
                'religion' => 'Islam',
                'address' => 'Jorong Tangah Muaro',
                'father_name' => 'Fri Dones',
                'mother_name' => 'Sri Astuti',
                'rombel' => '8/2',
            ],
        ];

        // 2. Pastikan Tahun Ajaran Aktif Ada
        $activePeriod = AcademicPeriod::where('is_active', true)->first();
        if (!$activePeriod) {
            $activePeriod = AcademicPeriod::create([
                'name' => '2025/2026 Ganjil',
                'start_date' => '2025-07-01',
                'end_date' => '2025-12-31',
                'is_active' => true,
            ]);
        }

        // 3. Pastikan Role Student Ada
        $roleSiswa = Role::firstOrCreate(['name' => 'student']);

        // 4. Proses Looping
        foreach ($studentsData as $data) {

            // A. AMBIL & PISAHKAN DATA ROMBEL
            $rombelRaw = $data['rombel'] ?? null;
            unset($data['rombel']);

            // B. LOGIKA KELAS (Classroom)
            $classroom = null;
            if ($rombelRaw) {
                // Ubah "7/1" menjadi "Kelas 7.1"
                $rombelName = str_replace('/', '.', $rombelRaw);

                // Ambil angka depan sebagai grade (7/1 -> 7)
                $gradeParts = explode('/', $rombelRaw);
                $grade = (int) $gradeParts[0];

                // Cari atau Buat Kelas
                $classroom = Classroom::firstOrCreate(
                    ['name' => "Kelas " . $rombelName], // Contoh: Kelas 9.1
                    ['grade_level' => $grade]
                );
            }

            // C. LOGIKA USER LOGIN
            $username = !empty($data['nisn']) ? $data['nisn'] : ($data['nipd'] ?? rand(10000, 99999));
            $username = preg_replace('/[^0-9]/', '', $username);

            $user = User::firstOrCreate(
                ['email' => "$username@sekolah.com"],
                [
                    'name' => $data['name'],
                    'password' => Hash::make('siswa123'),
                    'role' => 'student',
                    'is_active' => true,
                ]
            );
            $user->assignRole($roleSiswa);

            // D. LOGIKA SISWA (STUDENT)
            $studentData = array_merge($data, [
                'user_id' => $user->id,
                'status' => 'active',
            ]);

            $student = Student::updateOrCreate(
                ['user_id' => $user->id],
                $studentData
            );

            // E. LOGIKA PENDAFTARAN (ENROLLMENT)
            if ($classroom) {
                // Gunakan updateOrCreate untuk menghindari "Integrity constraint violation"
                // Jika kombinasi Siswa + Tahun Ajaran sudah ada, kita update saja kelasnya.
                Enrollment::updateOrCreate(
                    [
                        'student_id' => $student->id,
                        'academic_period_id' => $activePeriod->id, // Kunci Unik: 1 Siswa hanya boleh ada 1 record per Tahun
                    ],
                    [
                        'classroom_id' => $classroom->id, // Update ke kelas yang benar sesuai Excel
                        'status' => 'active'
                    ]
                );
            }
        }
    }
}